---
- name: Installing Virtual BMC and its requirements
  delegate_to: "{{ vbmc_inventory_host }}"
  block:
  - name: Gather facts (needed for install and iptables tasks)
    setup:

  # bandini (bos lab sucks)
  # When you install with ipv6 and tls-everywhere we get 2620:52:0:13b8:... on the external
  # interface (eth2). Since openstack.org web stuff is ipv6 ready, we will try to download upper
  # constraints for a long time untile we time out and then rety on ipv4 which will succeed
  # let's just ignore ipv6 for now
  - name: Create ipv4-forcing gai.conf
    become: true
    shell: "echo -ne 'scopev4 ::ffff:169.254.0.0/112  2\nscopev4 ::ffff:127.0.0.0/104    2\nscopev4 ::ffff:0.0.0.0/96       14\nprecedence ::ffff:0:0/96 100' > /etc/gai.conf"

  - name: Install packages required for python-virtualbmc pip package
    vars:
      _is_py2_host: "{{ ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_major_version | int < 8 }}"
    package:
      name:
        - ipmitool
        - libvirt-devel
        - "{{ (_is_py2_host | bool) | ternary('libvirt-python', 'python3-libvirt') }}"
      state: present
    become: true
    register: _install_packages
    until: _install_packages is success
    retries: 5
    delay: 10

  - name: Prepare the virtualenv
    include_role:
      name: create_venv
    vars:
      venv_constraints_remove:
        - "^libvirt-python.*$"
      venv_destination_path: "{{ vbmc_virtualenv }}"
      venv_pip_packages:
        - virtualbmc
      venv_rebuild: yes
      venv_system_site_packages: yes

  # When a virtualenv is setup, it does not copy the selinux labels.
  # ref: https://github.com/pypa/virtualenv/issues/1334
  - name: Set the correct label on the virtualenv to allow systemd to start the service
    file:
      path: "{{ vbmc_virtualenv }}/bin"
      state: directory
      setype: "bin_t"
      recurse: yes

  - name: Setup virtualbmc service
    become: true
    block:
    - name: Create virtualbmc systemd service
      copy:
        mode: 0664
        dest: "/etc/systemd/system/virtualbmc.service"
        content: |
          [Unit]
          Description=Virtual Baseboard Management Controller Emulation service
          After=syslog.target network.target

          [Service]
          Type=simple
          User={{ vbmc_user }}
          ExecStart={{ vbmc_virtualenv }}/bin/python {{ vbmcd_bin }} --foreground
          Restart=always
          RestartSec=1

          [Install]
          WantedBy=multi-user.target

    - name: Create virtualbmc required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0640
        owner: root
        group: root
      with_items:
        - "/etc/virtualbmc"
        - "/var/log/virtualbmc"

    - name: Create virtualbmc configuration file
      copy:
        mode: 0640
        dest: "/etc/virtualbmc/virtualbmc.conf"
        content: |
          [default]
          config_dir= {{ vbmc_config_dir }}
          [log]
          logfile=/var/log/virtualbmc/virtualbmc.log
          debug=True
          [ipmi]
          session_timout=20

    - name: Restart virtualbmc service
      service:
        name: virtualbmc
        state: restarted
        enabled: yes
        daemon_reload: yes
